<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robobaton_4p_ros2_demo</name>
  <version>1.3.1</version>
  <description>ROS2 demo that publishes RoboBaton 4P SC132 camera images and ICM-42688 IMU samples.</description>
  <maintainer email="taolong.xia@hessian-matrix.com">RoboBaton</maintainer>
  <license>Apache-2.0</license>
  <license>LicenseRef-RoboBaton-Vendor-Binary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>rcl_interfaces</depend>
  <depend>image_transport</depend>
  <depend>pluginlib</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
